"""Agrego room_id a message

Revision ID: 23e3892d51c7
Revises: 2e94174fa6dd
Create Date: 2025-07-08 00:48:45.716517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e3892d51c7'
down_revision: Union[str, Sequence[str], None] = '2e94174fa6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'room_id')
    # ### end Alembic commands ###
